package org.jlibvips;

public enum VipsForeignTiffCompression {
    VIPS_FOREIGN_TIFF_COMPRESSION_NONE,
    VIPS_FOREIGN_TIFF_COMPRESSION_JPEG,
    VIPS_FOREIGN_TIFF_COMPRESSION_DEFLATE,
    VIPS_FOREIGN_TIFF_COMPRESSION_PACKBITS,
    VIPS_FOREIGN_TIFF_COMPRESSION_CCITTFAX4,
    VIPS_FOREIGN_TIFF_COMPRESSION_LZW,
    VIPS_FOREIGN_TIFF_COMPRESSION_WEBP,
    VIPS_FOREIGN_TIFF_COMPRESSION_ZSTD,
    VIPS_FOREIGN_TIFF_COMPRESSION_LAST
}
